### ISSUE TITLE
Questions about Kajiri Kamui Kagura Akebono no Hikari

### ISSUE THREAD

**Issue by Akaruzi** [Monaco-a-Knox/Dia-da-Ira#1]
Hello, Monaco-a-Knox,  

I saw your vndb release of Kajiri Kamui Kagura Akebono no Hikari in Portuguese language. In the progess picture you shared, it seems that your patch successfully converted the vertical text to horizontal text.

I'm courious to know if it's possible to make a separate patch to achieve the conversion of vertical to horizontal text? Additionally, could you please provide some insights into how your patch achieved this?

Thank you!

Akaruzi
A Chinese fan of Shinza Banshou Series

**Comment by Monaco-a-Knox** [comment]
Hello. 

KKK is being translated by a friend, and I don't even know if he'll ever finish it, so I haven't touched it much yet, but it's actually very easy. Open "exec.str.txt" and edit a few lines. Search for "msgframe type" and type "horizontal". (1 line). Then search for "msgframe src" and type "novel". (5 lines). I still don't know how to make the choices horizontal.

Surprisingly, this game does have an NVL mode text box, but it's very dark. I recommend setting the transparency to maximum.

Unfortunately, since this game is breaking text by last character, not by last space, you have to insert linebreaks manually by adding [n] when necessary.

Translating the prologue is more complicated, so I plan to make a video with subtitles (there are four letters). I still don't know how to insert it into the game. To add translated images, you'll need to convert them to .dzi.

**Comment by Monaco-a-Knox** [comment]
Or you could do what the friend above suggested, which seems to work better.

**Comment by Cosetto** [comment]
Um, Idk, you have to test yourself. Note that the width, height above are textbox size, while the below are maximum text/line and text's length/textbox

**Comment by Monaco-a-Knox** [comment]
I used the same values for "normal_l" and textbox got bigger, but "normal_r" is still the same size, even though I changed the numbers... I must be doing something very stupid...

And how do you make "select.svg" horizontal? I tried modifying this file last year, but nothing I tried worked.

![image](https://github.com/Monaco-a-Knox/Dia-da-Ira/assets/58667780/f068e892-d774-495a-9b44-dee536486548)

**Comment by Cosetto** [comment]
I haven't tried with choice yet, but I think it should be in screen/select?

**Comment by Akaruzi** [comment]
I choose dir='normal', src='normal' which looks good in Chinese.
![图片](https://github.com/Monaco-a-Knox/Dia-da-Ira/assets/119655555/7996bb4c-ff7f-4c9f-b809-29040f5dcf31)

As for the prologue, you can use a PNG file to replace it. You just need to modify the .svg file and change the href link to point to a .png file.
![图片](https://github.com/Monaco-a-Knox/Dia-da-Ira/assets/119655555/ddf9e097-28db-4aa4-9734-5e10078a3f2e)

Since Chinese characters can be read horizontally, it won't take too much work. However, for English or Portuguese, it's necessary to modify x, y, width, and height.
![图片](https://github.com/Monaco-a-Knox/Dia-da-Ira/assets/119655555/0ad14069-2519-4cf0-a1e0-5a7ac67533d3)

**Comment by Cosetto** [comment]
> I choose dir='normal', src='normal' which looks good in Chinese. ![图片](https://private-user-images.githubusercontent.com/119655555/305608503-7996bb4c-ff7f-4c9f-b809-29040f5dcf31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNTU4NTIsIm5iZiI6MTcwODE1NTU1MiwicGF0aCI6Ii8xMTk2NTU1NTUvMzA1NjA4NTAzLTc5OTZiYjRjLWZmN2YtNGM5Zi1iODA5LTI5MDQwZjVkY2YzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QwNzM5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDFjZWY5ZGEyN2QzNjJkYjNlZGMyZGUwMTY0NDY3ZTIwZWRmNjczODI3MzUxMTgxNGRiYmUyZTg4ZGNlNGQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2QG_apW5Xxy6keJufDFqhO4Rwcjb3eHc_Sz4lDO1lYw)
> 
> As for the prologue, I found out it can replaced with a png file. We just need to modify the .svg file and change the href link to point to a .png file. ![图片](https://private-user-images.githubusercontent.com/119655555/305608528-ddf9e097-28db-4aa4-9734-5e10078a3f2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNTU4NTIsIm5iZiI6MTcwODE1NTU1MiwicGF0aCI6Ii8xMTk2NTU1NTUvMzA1NjA4NTI4LWRkZjllMDk3LTI4ZGItNGFhNC05NzM0LTVlMTAwNzhhM2YyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QwNzM5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmQ3MTFhYzYwNzRjZjkyYTA3NjhmYmEzOGFhMmMzMTM5ZThmODA5MzViNTQ0YWU4NGU3YjAyMTg3ZWJmZjU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Aly93p01vfDh6ck7Mc0EEOJVizPYwU6rsHEvgPfqPBs)
> 
> Since Chinese characters can be read horizontally, it won't take too much work. However, for English or Portuguese, it's necessary to modify x, y, width, and height. ![图片](https://private-user-images.githubusercontent.com/119655555/305608554-0ad14069-2519-4cf0-a1e0-5a7ac67533d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNTU4NTIsIm5iZiI6MTcwODE1NTU1MiwicGF0aCI6Ii8xMTk2NTU1NTUvMzA1NjA4NTU0LTBhZDE0MDY5LTI1MTktNGNmMC1hMWUwLTVhN2FjNjc1MzNkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QwNzM5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDRiMjFjZWQyYWU3NTIyODIxNjI3ODBlMzIyZWMzOTU4M2FkNTkxMDkzOGVkNDBlNmQ5OGE5MTcwMWI3OGM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ji7aWwCQTu8-x0FbA25iBedAOfm6VFZUmtT7hzO8HAI)
> 
> Thanks for your help.

Can you give me the png for the 1st pic?

**Comment by Akaruzi** [comment]
![图片](https://github.com/Monaco-a-Knox/Dia-da-Ira/assets/119655555/a41a9e3c-f9a9-4a5d-9b17-f00ac6a69489)
The href link can be changed into a png file as same as prologue.
What is really matter is 'y', it relates to the height of message box.

**Comment by Cosetto** [comment]
So this issue should be closed now?
Also @Akaruzi, since you're doing Akebono no Hikari, this version.dll should help bypassing the alpharom without using alpharomdie. Just run the game.exe directly.
[Version.zip](https://github.com/Monaco-a-Knox/Dia-da-Ira/files/14318278/Version.zip)

**Comment by Akaruzi** [comment]
Okay, I'll close it now.
The .dll file works well. Thank you so much！

**Comment by Akaruzi** [comment]
@Cosetto @Monaco-a-Knox Hey friends, I finally complete my k3 Chinese translation. Thanks for your help. 
誠にありがとうございます！

And Deca,  it's great to see your translation of Dies almost get finished. Since you may begin with k3 soon, I've write [something](https://github.com/Akaruzi/kkk_r18_patch/blob/master/entrans_tutorial.md) that might be helpful.

**Comment by Monaco-a-Knox** [comment]
Congratulations, and fantastic.

But I'm having trouble running epic.py... I need to install something?

And I have a few questions:

Why does ww.py always create a useless test file? And why not use msgothic?

And how did you deal with 神代文字? My idea was to use ruby, but it doesn't work in vertical mode.

**Comment by Akaruzi** [comment]
> But I'm having problem to run epic.py... I need to install something?

For modules you just need PIL and wordwrap. And it's necessary to clone the whole folder to run it. You just need to edit the tgm1_en.txt file to generate the pics and .svg file in the 'new' folder.

> Why does ww.py always create a useless test file? And why not use msgothic?
I didn't delete the test code, but it won't matter. You just need put you exec.msg file in the folder called script, and the new wordwraped file will be generated in the script_done folder.

And yes, I've tried msgothic. But I don't know why the letters font width is all the same. So I choose to use arial font. If you are interested, you can try some other font.

> And how did you deal with 神代文字? My idea was to use ruby, but it doesn't work in vertical mode.

And about Jindai moji, It's okay to use ruby with the syntax like `[jindaimoji code](text)`. But one thing you need to be aware of is that if other [ or ] is filled in the '[ ]' the jindaimoji conversion won't work. So you have to delete all the jindai moji code which contains [], like [n], [s], [c], [r]. You can see the jindai trans dict I have make in the k3 repo. 

like this, I delete all [n]

![图片](https://github.com/user-attachments/assets/d32576ba-9ef3-4459-8675-c82561c165d2)

![图片](https://github.com/user-attachments/assets/2c7705d9-ef4b-439e-9471-1f189a9ebebe)

And by the way, can I add your discord Deca？my account is akaru6139

**Comment by Cosetto** [comment]
Saw you on Madaverse Lobby

**Comment by Akaruzi** [comment]
> Saw you on Madaverse Lobby

you mean deem's server? yes, I'm trying to help with some k3 pictures edition like the sakuya‘s letters.
